// <auto-generated />
using System;
using KanbanApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanbanApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("KanbanApp.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Przykładowa tablica do testowania funkcjonalności kanban",
                            Name = "Demo Board"
                        });
                });

            modelBuilder.Entity("KanbanApp.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDone = true,
                            TaskItemId = 2,
                            Text = "Zidentyfikować encje"
                        },
                        new
                        {
                            Id = 2,
                            IsDone = true,
                            TaskItemId = 2,
                            Text = "Narysować diagram ERD"
                        },
                        new
                        {
                            Id = 3,
                            IsDone = false,
                            TaskItemId = 2,
                            Text = "Zdefiniować indeksy"
                        });
                });

            modelBuilder.Entity("KanbanApp.Models.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("Order");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            Color = "#6366f1",
                            Name = "Do zrobienia",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            Color = "#f59e0b",
                            Name = "W toku",
                            Order = 1,
                            WipLimit = 3
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            Color = "#22c55e",
                            Name = "Gotowe",
                            Order = 2
                        });
                });

            modelBuilder.Entity("KanbanApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3b82f6",
                            Name = "backend"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#6366f1",
                            Name = "frontend"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#8b5cf6",
                            Name = "db"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ec4899",
                            Name = "design"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#16a34a",
                            Name = "devops"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#d97706",
                            Name = "setup"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#0891b2",
                            Name = "testing"
                        });
                });

            modelBuilder.Entity("KanbanApp.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("Order");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ustawić GitHub Actions dla automatycznego budowania i testów",
                            Order = 0,
                            Priority = 2,
                            Title = "Skonfigurować CI/CD pipeline"
                        },
                        new
                        {
                            Id = 2,
                            ColumnId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Utworzyć diagram ERD i zdefiniować relacje między tabelami",
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 1,
                            Priority = 3,
                            Title = "Zaprojektować schemat bazy danych"
                        },
                        new
                        {
                            Id = 3,
                            ColumnId = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Formularz logowania z walidacją i obsługą błędów",
                            Order = 0,
                            Priority = 1,
                            Title = "Zaimplementować stronę logowania"
                        },
                        new
                        {
                            Id = 4,
                            ColumnId = 3,
                            CompletedAt = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Order = 0,
                            Priority = 0,
                            Title = "Dodać testy jednostkowe dla modeli"
                        });
                });

            modelBuilder.Entity("TagTaskItem", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("TaskItemTag", (string)null);

                    b.HasData(
                        new
                        {
                            TagsId = 5,
                            TasksId = 1
                        },
                        new
                        {
                            TagsId = 6,
                            TasksId = 1
                        },
                        new
                        {
                            TagsId = 2,
                            TasksId = 3
                        },
                        new
                        {
                            TagsId = 4,
                            TasksId = 3
                        });
                });

            modelBuilder.Entity("KanbanApp.Models.ChecklistItem", b =>
                {
                    b.HasOne("KanbanApp.Models.TaskItem", "TaskItem")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("KanbanApp.Models.Column", b =>
                {
                    b.HasOne("KanbanApp.Models.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("KanbanApp.Models.TaskItem", b =>
                {
                    b.HasOne("KanbanApp.Models.Column", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("TagTaskItem", b =>
                {
                    b.HasOne("KanbanApp.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanApp.Models.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KanbanApp.Models.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("KanbanApp.Models.Column", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("KanbanApp.Models.TaskItem", b =>
                {
                    b.Navigation("ChecklistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
